### ISSUE TITLE
Melhorar posicionamento do "links importantes"

### ISSUE THREAD

**Issue by jomaro** [PETComputacaoUFPR/pet-css#3]
dar um espaço maior do elemento da esquerda e melhor/tirar os marcadores de lista

**Comment by VytorCalixto** [comment]
Dobrei a margem esquerda e mudei os bullets. Testei sem, mas não ficou bacana. Que cê acha?

**Comment by jomaro** [comment]
nem notei :P 

fiz um teste colocando 10px de padding naquela div e achei legal o espaçamento, mas quebrou legal a tipografia. Tentei tirar os bullets pra ver se dava um jeito, mas não consegui, alias eles teoricamente já não estavam lá quando eu tentei tirar #quebruxariaeessa

fiz o mesmo com a div de conteúdo das postagens e achei o resultado legal

**Comment by VytorCalixto** [comment]
É, o bullets estavam e não estavam lá, mas agora eu tirei de verdade e, se eu eu entendi direito, coloquei um padding no conteúdo das postagens na home.

**Comment by jomaro** [comment]
aew
